In [2]:
from sklearn.datasets import load_breast_cancer 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score

In [3]:
data = load_breast_cancer()
X, y = data.data, data.target

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [5]:
model = LogisticRegression(max_iter=500)
model.fit(X_train, y_train)


c:\Users\Garod\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=500)

In [6]:
preds = model.predict(X_test)
accuracy = accuracy_score(y_test, preds)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.9561


In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("lr", LogisticRegression(max_iter=500))
])

pipe.fit(X_train, y_train)

preds = pipe.predict(X_test)
print("Scaled Accuracy:", accuracy_score(y_test, preds))


Scaled Accuracy: 0.9736842105263158


SCALING THE FEATURES IMPROVES THE ACCURACY IN LOGISTIC REGRESSION 


In [ ]:
probs = pipe.predict_proba(X_test)[:5]
print(probs)
#Column 0 → probability of class 0
#Column 1 → probability of class 1

[[1.14327437e-01 8.85672563e-01]
 [9.99990961e-01 9.03924655e-06]
 [9.96901657e-01 3.09834256e-03]
 [5.10962742e-04 9.99489037e-01]
 [6.08832659e-05 9.99939117e-01]]


In [9]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, preds)
print(cm)


[[41  2]
 [ 1 70]]


In [14]:
from sklearn.metrics import classification_report

print(classification_report(y_test, preds))


              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



## sigmoid and cross entropy formulas practice

In [15]:
import numpy as np

In [16]:
def sigmoid(z):
    return 1/(1+np.exp(-z))
z = np.array([-2, -1, 0, 1, 2])
print(sigmoid(z))   

[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [17]:
def binary_cross_entropy(y_true,y_pred):
    return -np.mean(y_true*np.log(y_pred) + (1-y_true)*np.log(1-y_pred))
y_true = np.array([1, 0, 1, 1, 0])
y_pred = np.array([0.9, 0.1, 0.8, 0.7, 0.2])
loss= binary_cross_entropy(y_true, y_pred)
print(f"Binary Cross-Entropy Loss: {loss:.4f}")

Binary Cross-Entropy Loss: 0.2027
